### ISSUE TITLE
Use of non existent class in Map class

### ISSUE THREAD

**Issue by Dam62** [Smile-SA/magento2-module-store-locator#13]
Hello,

It seems that you use a class that no longer exists in version 1.2.x (Smile\StoreLocator\Block\Retailer\AbstractView) in class Map.

https://github.com/Smile-SA/magento2-module-store-locator/blob/1.2.x/Block/View/Map.php#L16

Regards,

**Comment by romainruaud** [comment]
You are right, the "use" statement seems to be wrong.

However, since the "extends" is using the fully qualified class name, this should work properly.

Do you have an error ? I did not test for the moment but I suspect this could provoke a bug during the compilation process, is this your case ?

I will provide a fix soon for this one in branch 1.2.x, or better, maybe you can propose a PR removing this wrong statement ;)

**Comment by romainruaud** [comment]
Fixed in 1.2.x and 1.3.x branches.
